-- migration_023 — Pack bibliographique « Droit des obligations ».
--
-- Les PDF transmis contiennent des ouvrages édités et des supports
-- pédagogiques. Cette migration publie les notices, plans et synthèses
-- originales du pack, sans reproduire les ouvrages intégralement.
-- Les fichiers présentant le même ouvrage sous plusieurs scans sont
-- dédoublonnés ici.

insert into public.legal_documents (
  id, title, type, domain, reference, date_publication, status, summary,
  full_content, outline, summary_only, official_source_name, source_url,
  tags, related_ids, imported_at
)
values
('doc-doctrine-terre-obligations',
 'Droit civil — Les obligations', 'doctrine', 'civil',
 'François Terré, Philippe Simler, Yves Lequette, François Chénedé — 12e éd. refondue, Dalloz, 2019',
 '2019-01-01', 'enVigueur',
 'Traité de référence consacré aux sources des obligations, au contrat, à la responsabilité extracontractuelle et au régime général des obligations. À consulter comme doctrine et non comme texte normatif en vigueur.',
 '',
 array['Livre 1 — Les sources des obligations', 'Titre 1 — Le contrat', 'Titre 2 — La responsabilité extracontractuelle', 'Titre 3 — Les régimes spéciaux de responsabilité', 'Livre 2 — Le régime général des obligations', 'Livre 3 — Les contrats spéciaux'],
 true, 'Ouvrage doctrinal transmis par l’équipe JurisIA', null,
 array['pack-obligations', 'droit des obligations', 'contrat', 'responsabilité civile', 'régime général', 'doctrine'],
 array[]::text[], now()),
('doc-doctrine-porchy-simon-obligations',
 'Droit civil, 2e année — Les obligations', 'doctrine', 'civil',
 'Stéphanie Porchy-Simon — HyperCours, 9e éd., Dalloz, 2016',
 '2016-01-01', 'enVigueur',
 'Cours et travaux dirigés structurés autour du contrat, de la responsabilité civile, des quasi-contrats et du régime général des obligations, avec des outils de révision et d’entraînement.',
 '',
 array['Partie 1 — Le contrat', 'Partie 2 — La responsabilité civile', 'Partie 3 — Les quasi-contrats', 'Partie 4 — Le régime général des obligations', 'Travaux dirigés — Méthodes, documents et exercices'],
 true, 'Ouvrage doctrinal transmis par l’équipe JurisIA', null,
 array['pack-obligations', 'droit civil', 'cours', 'travaux dirigés', 'révision'],
 array[]::text[], now()),
('doc-annales-obligations-dalloz',
 'Droit civil des obligations — Méthodologie & sujets corrigés', 'doctrine', 'civil',
 'Annick Batteur (dir.) — Les Annales du droit, Dalloz, 2017',
 '2017-01-01', 'enVigueur',
 'Recueil méthodologique destiné à l’entraînement : étude de cas, consultation, commentaire, dissertation et sujets corrigés portant notamment sur la formation et l’inexécution du contrat.',
 '',
 array['Introduction au droit civil des obligations', 'Méthodologie — Cas pratique et consultation', 'Méthodologie — Commentaire et dissertation', 'Sujets corrigés — Formation du contrat', 'Sujets corrigés — Inexécution du contrat', 'Sujets corrigés — Responsabilité civile'],
 true, 'Ouvrage pédagogique transmis par l’équipe JurisIA', null,
 array['pack-obligations', 'annales', 'méthodologie juridique', 'cas pratique', 'commentaire d’arrêt'],
 array[]::text[], now()),
('doc-technique-contractuelle-meyer',
 'Technique contractuelle', 'doctrine', 'civil',
 'Pierre Meyer — Cours de Master 2, Droit des affaires et fiscalité, Université Ouaga 2',
 '2020-01-01', 'enVigueur',
 'Support pédagogique consacré à la négociation, à la conclusion, à la rédaction et à l’exécution des contrats, avec un éclairage OHADA et des réflexes de pratique contractuelle.',
 '',
 array['Titre I — La négociation et la conclusion du contrat', 'Titre II — La rédaction et la structure contractuelle', 'Titre III — L’exécution et la fin du contrat', 'Pratique contractuelle en contexte OHADA'],
 true, 'Support universitaire transmis par l’équipe JurisIA', null,
 array['pack-obligations', 'technique contractuelle', 'négociation', 'rédaction contractuelle', 'OHADA'],
 array[]::text[], now()),
('doc-gorlier-contrats-speciaux',
 'Droit des contrats spéciaux', 'doctrine', 'civil',
 'Vincent Gorlier — Ellipses, ouvrage de synthèse et d’entraînement',
 '2020-01-01', 'enVigueur',
 'Fiches de synthèse sur les principaux contrats spéciaux, leurs critères de qualification, leurs régimes et les décisions utiles à la compréhension de la matière.',
 '',
 array['Notions générales des contrats spéciaux', 'Contrats portant sur une chose', 'Contrats portant sur un service', 'Contrats de distribution et contrats d’affaires', 'Cas pratiques et outils de révision'],
 true, 'Ouvrage doctrinal transmis par l’équipe JurisIA', null,
 array['pack-obligations', 'contrats spéciaux', 'vente', 'bail', 'mandat', 'révision'],
 array[]::text[], now()),
('doc-malaurie-contrats-speciaux',
 'Droit des contrats spéciaux', 'doctrine', 'civil',
 'Philippe Malaurie, Laurent Aynès, Pierre-Yves Gautier — 8e éd., LGDJ/Lextenso, 2016',
 '2016-01-01', 'enVigueur',
 'Étude doctrinale des contrats de la vie patrimoniale : vente, mandat, bail, échange, distribution, dépôt, prêt, transaction et arbitrage, replacés dans leur environnement légal et jurisprudentiel.',
 '',
 array['Théorie générale et qualification des contrats spéciaux', 'Contrats translatifs de propriété', 'Contrats portant sur la jouissance d’une chose', 'Contrats de services et de distribution', 'Dépôt, prêt, transaction et arbitrage'],
 true, 'Ouvrage doctrinal transmis par l’équipe JurisIA', null,
 array['pack-obligations', 'contrats spéciaux', 'vente', 'bail', 'distribution', 'transaction'],
 array[]::text[], now()),
('doc-renault-brahinsky-obligations-mementos',
 'Droit des obligations', 'doctrine', 'civil',
 'Corinne Renault-Brahinsky — Mémentos, 16e éd., Gualino, 2019/2020',
 '2019-01-01', 'enVigueur',
 'Cours synthétique couvrant les principes généraux de l’obligation, le contrat, la responsabilité civile, les quasi-contrats et les opérations du régime général.',
 '',
 array['Principes généraux relatifs à l’obligation', 'Le contrat et ses effets', 'La responsabilité civile et le fait juridique', 'Les quasi-contrats', 'Le régime général des obligations'],
 true, 'Ouvrage doctrinal transmis par l’équipe JurisIA', null,
 array['pack-obligations', 'droit des obligations', 'cours synthétique', 'responsabilité civile', 'quasi-contrats'],
 array[]::text[], now()),
('doc-boustani-contrats-speciaux',
 'L’essentiel du droit des contrats spéciaux', 'doctrine', 'civil',
 'Diane Boustani — 2e éd. 2020-2021, Les Carrés, Gualino',
 '2020-01-01', 'enVigueur',
 'Synthèse pratique des contrats spéciaux : transfert de propriété, utilisation d’une chose, services, distribution, transport et règlement des litiges.',
 '',
 array['Introduction — Notions générales', 'Contrats translatifs de propriété — Vente et échanges', 'Contrats portant sur l’utilisation d’une chose', 'Contrats portant sur des services', 'Contrats de distribution et contrats de règlement des litiges'],
 true, 'Ouvrage doctrinal transmis par l’équipe JurisIA', null,
 array['pack-obligations', 'contrats spéciaux', 'vente', 'bail', 'services', 'distribution'],
 array[]::text[], now()),
('doc-renault-brahinsky-obligations-essentiel',
 'L’essentiel du droit des obligations', 'doctrine', 'civil',
 'Corinne Renault-Brahinsky — 16e éd. 2020-2021, Les Carrés, Gualino',
 '2020-01-01', 'enVigueur',
 'Synthèse de révision en quatre axes : contrat, responsabilité civile, quasi-contrats et régime général des obligations, avec repères sur la réforme du droit des contrats.',
 '',
 array['Le contrat', 'La responsabilité civile', 'Les quasi-contrats', 'Le régime général des obligations', 'Repères de réforme et de méthode'],
 true, 'Ouvrage doctrinal transmis par l’équipe JurisIA', null,
 array['pack-obligations', 'droit des obligations', 'révision', 'contrat', 'responsabilité civile'],
 array[]::text[], now())
on conflict (id) do update set
  title = excluded.title,
  type = excluded.type,
  domain = excluded.domain,
  reference = excluded.reference,
  date_publication = excluded.date_publication,
  status = excluded.status,
  summary = excluded.summary,
  full_content = excluded.full_content,
  outline = excluded.outline,
  summary_only = excluded.summary_only,
  official_source_name = excluded.official_source_name,
  source_url = excluded.source_url,
  tags = excluded.tags,
  related_ids = excluded.related_ids,
  imported_at = excluded.imported_at;
