-- migration_035 — PDF intégraux du pack droit commercial et sociétés.
-- Les deux fichiers Droit commercial_2015_ sont identiques ; un seul est catalogué.

do $catalog$
declare
  base_url constant text :=
    'https://gfpguuuzzyqoxjkhlhli.supabase.co/storage/v1/object/public/legal-source-pdfs/';
begin
  insert into public.legal_documents (
    id, title, type, domain, reference, date_publication, status, summary,
    full_content, outline, summary_only, official_source_name, file_url,
    tags, related_ids, imported_at
  )
  values
  ('pdf-commercial-assogba-2023', 'Cours de droit commercial — Dr Assogba', 'doctrine', 'commercial',
   'Cours du Dr Assogba — novembre 2023', '2023-11-01', 'enVigueur',
   'Cours de droit commercial transmis à JurisIA.', '', '{}', false, 'Document transmis à JurisIA',
   base_url || 'COURS%20DE%20DROIT%20COMMERCIAL%20Dr%20ASSOGBA%20Nov%2023.pdf',
   array['pack-droit-commercial-societes', 'droit commercial', 'cours', 'Dr Assogba', 'PDF intégral'], '{}', now()),
  ('pdf-commercial-general-partie-3', 'Droit commercial général — troisième partie', 'doctrine', 'commercial',
   'Cours de droit commercial général — partie 3', '2023-01-01', 'enVigueur',
   'Troisième partie du cours de droit commercial général.', '', '{}', false, 'Document transmis à JurisIA',
   base_url || 'Cours%20Droit%20commercial%20gnral%2C%203e%20partie.pdf',
   array['pack-droit-commercial-societes', 'droit commercial général', 'cours', 'PDF intégral'], '{}', now()),
  ('pdf-commercial-l3-cj', 'Droit commercial — cours L3 CJ', 'doctrine', 'commercial',
   'Cours de droit commercial — niveau L3 CJ', '2023-01-01', 'enVigueur',
   'Cours de droit commercial destiné au niveau L3 CJ.', '', '{}', false, 'Document transmis à JurisIA',
   base_url || 'Cours_Droit%20commercial_L3%20CJ.pdf',
   array['pack-droit-commercial-societes', 'droit commercial', 'cours L3', 'PDF intégral'], '{}', now()),
  ('pdf-commercial-affaires-mementos-lmd', 'Droit commercial et des affaires — Mémentos LMD', 'doctrine', 'commercial',
   'Droit commercial et des affaires — Mémentos LMD', '2020-01-01', 'enVigueur',
   'Ouvrage de référence consacré au droit commercial et des affaires.', '', '{}', false, 'Document transmis à JurisIA',
   base_url || 'Droit%20commercial%20et%20des%20affaires-Mmotos%20LMD.pdf',
   array['pack-droit-commercial-societes', 'droit des affaires', 'mémentos LMD', 'PDF intégral'], '{}', now()),
  ('pdf-commercial-societes-afrique', 'Droit commercial et des sociétés en Afrique', 'doctrine', 'commercial',
   'Droit commercial et droit des sociétés en Afrique', '2015-01-01', 'enVigueur',
   'Ouvrage consacré au droit commercial et aux sociétés en Afrique.', '', '{}', false, 'Document transmis à JurisIA',
   base_url || 'Droit%20commercial%20et%20des%20socits%20en%20Afrique.pdf',
   array['pack-droit-commercial-societes', 'droit des sociétés', 'Afrique', 'PDF intégral'], '{}', now()),
  ('pdf-commercial-societes-2015', 'Droit commercial et des sociétés — édition 2015', 'doctrine', 'commercial',
   'Édition 2015', '2015-01-01', 'enVigueur',
   'Cours de droit commercial et des sociétés, édition 2015.', '', '{}', false, 'Document transmis à JurisIA',
   base_url || 'Droit%20commercial%20et%20des%20socits_2015.pdf',
   array['pack-droit-commercial-societes', 'droit commercial', 'droit des sociétés', '2015', 'PDF intégral'], '{}', now()),
  ('pdf-commercial-general-ohada-cm', 'Droit commercial général OHADA — cours magistral', 'doctrine', 'commercial',
   'Cours magistral — droit commercial général OHADA', '2023-01-01', 'enVigueur',
   'Cours magistral consacré au droit commercial général OHADA.', '', '{}', false, 'Document transmis à JurisIA',
   base_url || 'DROIT%20COMMERCIAL%20GENERAL%20OHADA_CM-1.pdf',
   array['pack-droit-commercial-societes', 'OHADA', 'droit commercial général', 'cours magistral', 'PDF intégral'], '{}', now()),
  ('pdf-societes-merle-fauchon-2017', 'Droit commercial — sociétés commerciales', 'doctrine', 'commercial',
   'Philippe Merle et Anne Fauchon — Précis, 20e éd., Dalloz, 2017', '2017-01-01', 'enVigueur',
   'Précis consacré au droit des sociétés commerciales.', '', '{}', false, 'Document transmis à JurisIA',
   base_url || 'DROIT%20COMMERCIAL%20SOCIETES%20COMMERCIALES%20--%20Philippe%20Merle%3B%20Anne%20Fauchon%20--%20Prcis%2C%2020%2C%202017%20--%20Dalloz%20--%20013b1b2413a40587aa36b6885a311d72%20--%20Annas%20Archive.pdf',
   array['pack-droit-commercial-societes', 'droit des sociétés commerciales', 'Philippe Merle', 'Anne Fauchon', 'Dalloz', 'PDF intégral'], '{}', now()),
  ('pdf-commercial-2015', 'Droit commercial — édition 2015', 'doctrine', 'commercial',
   'Édition 2015', '2015-01-01', 'enVigueur',
   'Cours de droit commercial, édition 2015.', '', '{}', false, 'Document transmis à JurisIA',
   base_url || 'Droit%20commercial_2015_.pdf',
   array['pack-droit-commercial-societes', 'droit commercial', 'cours', '2015', 'PDF intégral'], '{}', now()),
  ('pdf-societes-ohada-akam-akam', 'Droit des sociétés commerciales OHADA', 'doctrine', 'commercial',
   'André Akam Akam et Voudwe — droit des sociétés commerciales OHADA', '2020-01-01', 'enVigueur',
   'Étude du droit OHADA des sociétés commerciales.', '', '{}', false, 'Document transmis à JurisIA',
   base_url || 'Droit_des_socits_commerciales_OHADA_de_Andr_Akam_Akam_Voudwe.pdf',
   array['pack-droit-commercial-societes', 'OHADA', 'droit des sociétés commerciales', 'PDF intégral'], '{}', now()),
  ('pdf-societes-grandguillot', 'L’essentiel du droit des sociétés', 'doctrine', 'commercial',
   'Béatrice et Francis Grandguillot — L’essentiel du droit des sociétés', '2020-01-01', 'enVigueur',
   'Ouvrage pédagogique consacré aux notions essentielles du droit des sociétés.', '', '{}', false, 'Document transmis à JurisIA',
   base_url || 'L%27essentiel_du_droit_des_societes_Beatrice_et_Francis_Grandguillot.pdf',
   array['pack-droit-commercial-societes', 'droit des sociétés', 'Béatrice Grandguillot', 'Francis Grandguillot', 'PDF intégral'], '{}', now()),
  ('pdf-societes-ohada-intervention-juge', 'L’intervention du juge dans le droit des sociétés commerciales OHADA', 'doctrine', 'commercial',
   'Étude de l’intervention judiciaire en droit des sociétés OHADA', '2020-01-01', 'enVigueur',
   'Étude du rôle du juge dans le droit OHADA des sociétés commerciales.', '', '{}', false, 'Document transmis à JurisIA',
   base_url || 'L%27intervention_du_juge_dans_le_droit_des_socits_commerciales_OHADA.pdf',
   array['pack-droit-commercial-societes', 'OHADA', 'droit des sociétés commerciales', 'jurisprudence', 'PDF intégral'], '{}', now())
  on conflict (id) do update set
    title = excluded.title,
    type = excluded.type,
    domain = excluded.domain,
    reference = excluded.reference,
    date_publication = excluded.date_publication,
    status = excluded.status,
    summary = excluded.summary,
    full_content = excluded.full_content,
    outline = excluded.outline,
    summary_only = false,
    official_source_name = excluded.official_source_name,
    file_url = excluded.file_url,
    tags = excluded.tags,
    related_ids = excluded.related_ids,
    updated_at = now();
end $catalog$;
