-- migration_031 — PDF intégraux du pack administratif.
-- Les fichiers sont déjà stockés dans le bucket public legal-source-pdfs.
-- Les doublons binaires du lot reçu sont volontairement représentés une seule fois.
do $catalog$
declare
  base_url constant text :=
    'https://gfpguuuzzyqoxjkhlhli.supabase.co/storage/v1/object/public/legal-source-pdfs/';
begin
  insert into public.legal_documents (
    id, title, type, domain, reference, status, summary, full_content,
    outline, summary_only, official_source_name, file_url, tags, related_ids,
    imported_at
  )
  values
  ('pdf-admin-jurisprudence-conseil-2024', 'Jurisprudence du Conseil d’État — 2024', 'jurisprudence', 'administratif',
   'Recueil de jurisprudence administrative, édition 2024', 'enVigueur',
   'PDF intégral — recueil de jurisprudence administrative.', '', '{}', false,
   'Document transmis par l’équipe JurisIA', base_url || 'admin-jurisprudence-conseil-2024.pdf',
   array['pack-droit-administratif', 'jurisprudence administrative', 'Conseil d’État', '2024', 'PDF intégral'], '{}', now()),
  ('pdf-admin-contentieux-fondation', 'Contentieux administratif — La fondation', 'doctrine', 'administratif',
   'Support de contentieux administratif transmis à JurisIA', 'enVigueur',
   'PDF intégral — support de contentieux administratif.', '', '{}', false,
   'Document transmis par l’équipe JurisIA', base_url || 'admin-contentieux-fondation.pdf',
   array['pack-droit-administratif', 'contentieux administratif', 'PDF intégral'], '{}', now()),
  ('pdf-admin-contentieux-minet-leleu', 'Le contentieux administratif — Alice Minet-Leleu', 'doctrine', 'administratif',
   'Le contentieux administratif en cartes mentales', 'enVigueur',
   'PDF intégral — ouvrage consacré au contentieux administratif.', '', '{}', false,
   'Document transmis par l’équipe JurisIA', base_url || 'admin-contentieux-minet-leleu.pdf',
   array['pack-droit-administratif', 'contentieux administratif', 'procédure administrative', 'PDF intégral'], '{}', now()),
  ('pdf-admin-arrets-jumeaux-1', 'Les arrêts jumeaux en droit administratif — volume 1/2', 'doctrine', 'administratif',
   'PDF intégral — pages 1 à 130 sur 260', 'enVigueur',
   'Première partie du PDF intégral, pages 1 à 130. Le découpage conserve l’ordre et la totalité des pages du document source.', '', '{}', false,
   'Document transmis par l’équipe JurisIA', base_url || 'admin-arrets-jumeaux-part-1.pdf',
   array['pack-droit-administratif', 'droit administratif', 'jurisprudence', 'PDF intégral', 'volume 1/2'], '{}', now()),
  ('pdf-admin-arrets-jumeaux-2', 'Les arrêts jumeaux en droit administratif — volume 2/2', 'doctrine', 'administratif',
   'PDF intégral — pages 131 à 260 sur 260', 'enVigueur',
   'Seconde partie du PDF intégral, pages 131 à 260. Le découpage conserve l’ordre et la totalité des pages du document source.', '', '{}', false,
   'Document transmis par l’équipe JurisIA', base_url || 'admin-arrets-jumeaux-part-2.pdf',
   array['pack-droit-administratif', 'droit administratif', 'jurisprudence', 'PDF intégral', 'volume 2/2'], '{}', now()),
  ('pdf-admin-cours-mpiana', 'Cours de droit administratif — Professeur Mpiana', 'doctrine', 'administratif',
   'Cours de droit administratif', 'enVigueur',
   'PDF intégral — cours de droit administratif.', '', '{}', false,
   'Document transmis par l’équipe JurisIA', base_url || 'admin-cours-mpiana.pdf',
   array['pack-droit-administratif', 'droit administratif', 'cours', 'PDF intégral'], '{}', now()),
  ('pdf-admin-dalloz', 'Droit administratif — Dalloz', 'doctrine', 'administratif',
   'Droit administratif — édition Dalloz', 'enVigueur',
   'PDF intégral — ouvrage de droit administratif.', '', '{}', false,
   'Document transmis par l’équipe JurisIA', base_url || 'admin-dalloz.pdf',
   array['pack-droit-administratif', 'droit administratif', 'doctrine', 'PDF intégral'], '{}', now()),
  ('pdf-admin-mboko', 'Droit administratif — Mboko', 'doctrine', 'administratif',
   'Cours de droit administratif', 'enVigueur',
   'PDF intégral — support de droit administratif.', '', '{}', false,
   'Document transmis par l’équipe JurisIA', base_url || 'admin-mboko.pdf',
   array['pack-droit-administratif', 'droit administratif', 'cours', 'PDF intégral'], '{}', now()),
  ('pdf-admin-contentieux-congolais', 'Précis du contentieux administratif congolais — tome 2', 'doctrine', 'administratif',
   'Tome 2 — contentieux administratif congolais', 'enVigueur',
   'PDF intégral — précis de contentieux administratif.', '', '{}', false,
   'Document transmis par l’équipe JurisIA', base_url || 'admin-contentieux-congolais-t2.pdf',
   array['pack-droit-administratif', 'contentieux administratif', 'Congo', 'PDF intégral'], '{}', now()),
  ('pdf-admin-cours-dieye', 'Cours de droit administratif — Abdoulaye Dièye', 'doctrine', 'administratif',
   'Cours de droit administratif', 'enVigueur',
   'PDF intégral — cours de droit administratif.', '', '{}', false,
   'Document transmis par l’équipe JurisIA', base_url || 'admin-cours-dieye.pdf',
   array['pack-droit-administratif', 'droit administratif', 'cours', 'PDF intégral'], '{}', now()),
  ('pdf-admin-grands-services-publics', 'Droit administratif — Les grands services publics de l’État', 'doctrine', 'administratif',
   'Les grands services publics de l’État', 'enVigueur',
   'PDF intégral — étude des services publics de l’État.', '', '{}', false,
   'Document transmis par l’équipe JurisIA', base_url || 'admin-grands-services-publics.pdf',
   array['pack-droit-administratif', 'droit administratif', 'services publics', 'PDF intégral'], '{}', now()),
  ('pdf-admin-frier', 'Droit administratif — Frier', 'doctrine', 'administratif',
   'Ouvrage de droit administratif', 'enVigueur',
   'PDF intégral — ouvrage de droit administratif.', '', '{}', false,
   'Document transmis par l’équipe JurisIA', base_url || 'admin-frier.pdf',
   array['pack-droit-administratif', 'droit administratif', 'doctrine', 'PDF intégral'], '{}', now()),
  ('pdf-admin-contentieux-notes-l3', 'Contentieux administratif — Notes de cours L3', 'doctrine', 'administratif',
   'Notes de cours L3 — droit complet', 'enVigueur',
   'PDF intégral — notes de cours de contentieux administratif.', '', '{}', false,
   'Document transmis par l’équipe JurisIA', base_url || 'admin-contentieux-notes-l3.pdf',
   array['pack-droit-administratif', 'contentieux administratif', 'cours', 'PDF intégral'], '{}', now()),
  ('pdf-admin-grands-arrets', 'Grands arrêts du droit administratif français', 'jurisprudence', 'administratif',
   'Recueil de grands arrêts administratifs', 'enVigueur',
   'PDF intégral — recueil consacré aux grands arrêts de droit administratif.', '', '{}', false,
   'Document transmis par l’équipe JurisIA', base_url || 'admin-grands-arrets.pdf',
   array['pack-droit-administratif', 'jurisprudence administrative', 'grands arrêts', 'PDF intégral'], '{}', now()),
  ('pdf-admin-contentieux-pratique', 'Contentieux administratif — support de cours', 'doctrine', 'administratif',
   'Support de contentieux administratif', 'enVigueur',
   'PDF intégral — support de contentieux administratif.', '', '{}', false,
   'Document transmis par l’équipe JurisIA', base_url || 'admin-contentieux-pratique.pdf',
   array['pack-droit-administratif', 'contentieux administratif', 'cours', 'PDF intégral'], '{}', now()),
  ('pdf-admin-ferretti', 'Le droit administratif — Raymond Ferretti', 'doctrine', 'administratif',
   'Cours de l’Université de Metz', 'enVigueur',
   'PDF intégral — cours de droit administratif.', '', '{}', false,
   'Document transmis par l’équipe JurisIA', base_url || 'admin-ferretti.pdf',
   array['pack-droit-administratif', 'droit administratif', 'cours', 'PDF intégral'], '{}', now()),
  ('pdf-admin-biens', 'Droit administratif des biens', 'doctrine', 'administratif',
   'Cours de droit administratif des biens', 'enVigueur',
   'PDF intégral — droit administratif des biens.', '', '{}', false,
   'Document transmis par l’équipe JurisIA', base_url || 'admin-droit-des-biens.pdf',
   array['pack-droit-administratif', 'droit administratif des biens', 'PDF intégral'], '{}', now()),
  ('pdf-admin-manuel-procedures-vraa', 'Manuel de procédures administratives — VRAA', 'rapport', 'administratif',
   'Manuel de procédures administratives', 'enVigueur',
   'PDF intégral — manuel de procédures administratives.', '', '{}', false,
   'Document transmis par l’équipe JurisIA', base_url || 'admin-manuel-procedures-vraa.pdf',
   array['pack-droit-administratif', 'procédures administratives', 'administration publique', 'PDF intégral'], '{}', now()),
  ('pdf-admin-etat-lieux-services-vraa', 'État des lieux et harmonisation des services — VRAA', 'rapport', 'administratif',
   'État des lieux et harmonisation des services', 'enVigueur',
   'PDF intégral — rapport sur l’état des lieux et l’harmonisation des services.', '', '{}', false,
   'Document transmis par l’équipe JurisIA', base_url || 'admin-etat-lieux-services-vraa.pdf',
   array['pack-droit-administratif', 'services publics', 'administration publique', 'PDF intégral'], '{}', now()),
  ('pdf-admin-juge-unique', 'Le juge unique dans le contentieux administratif des États', 'doctrine', 'administratif',
   'Étude du juge unique en contentieux administratif', 'enVigueur',
   'PDF intégral — étude sur le juge unique en contentieux administratif.', '', '{}', false,
   'Document transmis par l’équipe JurisIA', base_url || 'admin-juge-unique.pdf',
   array['pack-droit-administratif', 'contentieux administratif', 'juridictions administratives', 'PDF intégral'], '{}', now())
  on conflict (id) do update set
    title = excluded.title,
    type = excluded.type,
    domain = excluded.domain,
    reference = excluded.reference,
    status = excluded.status,
    summary = excluded.summary,
    full_content = excluded.full_content,
    outline = excluded.outline,
    summary_only = false,
    official_source_name = excluded.official_source_name,
    file_url = excluded.file_url,
    tags = excluded.tags,
    related_ids = excluded.related_ids,
    imported_at = excluded.imported_at,
    updated_at = now();
end $catalog$;
