import 'package:flutter/material.dart';

/// Typologie métier affichée dans le parcours « Services professionnels ».
///
/// Les demandes historiques peuvent encore contenir les anciennes catégories
/// de création d'entreprise. Elles sont normalisées vers [jurisconsult] afin
/// de ne pas casser les dossiers déjà enregistrés, mais l'interface expose
/// volontairement les quatre pôles professionnels principaux.
enum ProfessionalServiceCategory {
  notarial,
  lawyers,
  bailiffs,
  jurisconsult;

  static const primaryValues = <ProfessionalServiceCategory>[
    notarial,
    lawyers,
    bailiffs,
    jurisconsult,
  ];

  static ProfessionalServiceCategory fromName(String? name) {
    final normalized = name?.trim().toLowerCase();
    return switch (normalized) {
      'notaire' || 'services_notariaux' || 'notarial' => notarial,
      'avocat' || 'services_avocats' || 'lawyers' => lawyers,
      'huissier' || 'services_huissier' || 'bailiffs' => bailiffs,
      _ => jurisconsult,
    };
  }
}

extension ProfessionalServiceCategoryDetails on ProfessionalServiceCategory {
  String get slug => switch (this) {
    ProfessionalServiceCategory.notarial => 'services_notariaux',
    ProfessionalServiceCategory.lawyers => 'services_avocats',
    ProfessionalServiceCategory.bailiffs => 'services_huissier',
    ProfessionalServiceCategory.jurisconsult => 'jurisconsulte',
  };

  String get label => switch (this) {
    ProfessionalServiceCategory.notarial => 'Services notariaux',
    ProfessionalServiceCategory.lawyers => 'Services d’avocats',
    ProfessionalServiceCategory.bailiffs => 'Services d’huissier',
    ProfessionalServiceCategory.jurisconsult => 'Jurisconsulte',
  };

  String get description => switch (this) {
    ProfessionalServiceCategory.notarial =>
      'Actes authentiques, successions, immobilier et formalités notariales.',
    ProfessionalServiceCategory.lawyers =>
      'Conseil, contrats, défense et stratégie avec un avocat partenaire.',
    ProfessionalServiceCategory.bailiffs =>
      'Constats, significations, recouvrement et exécution des décisions.',
    ProfessionalServiceCategory.jurisconsult =>
      'Avis, recherches, rédaction, conformité et orientation juridique pour les dossiers complexes.',
  };

  IconData get icon => switch (this) {
    ProfessionalServiceCategory.notarial => Icons.account_balance_rounded,
    ProfessionalServiceCategory.lawyers => Icons.gavel_rounded,
    ProfessionalServiceCategory.bailiffs => Icons.markunread_mailbox_rounded,
    ProfessionalServiceCategory.jurisconsult => Icons.balance_rounded,
  };

  List<String> get serviceTypes => switch (this) {
    ProfessionalServiceCategory.notarial => const [
      'Acte de vente',
      'Acte de donation',
      'Acte de partage',
      'Acte de reconnaissance de dette',
      'Acte de prêt',
      'Acte de quittance',
      'Acte de mainlevée',
      'Acte de dépôt',
      'Acte de déclaration',
      'Acte de constitution de garantie',
      'Vente immobilière',
      'Donation immobilière',
      'Partage immobilier',
      'Cession de droits immobiliers',
      'Constitution d’hypothèque',
      'Procuration pour opération immobilière',
      'Contrat de mariage',
      'Convention matrimoniale',
      'Donation entre époux',
      'Reconnaissance d’enfant né hors mariage',
      'Acte de notoriété',
      'Déclaration de succession',
      'Inventaire successoral',
      'Acte de partage successoral',
      'Acceptation de succession',
      'Renonciation à succession',
      'Liquidation de succession',
      'Testament authentique',
      'Réception de testament',
      'Dépôt de testament',
      'Révocation de testament',
      'Prêt notarié',
      'Cautionnement',
      'Nantissement',
      'Acte relatif aux sociétés',
      'Cession de parts nécessitant un acte notarié',
      'Apports immobiliers',
      'Acte de transaction',
      'Protocole transactionnel reçu par notaire',
      'Procuration générale',
      'Procuration spéciale',
      'Procuration successorale',
      'Authentification d’actes',
      'Certification notariale',
      'Délivrance de copies d’actes',
      'Conservation des actes',
      'Consultation notariale',
      'Conseil patrimonial',
      'Préparation d’un dossier notarial',
    ],
    ProfessionalServiceCategory.lawyers => const [
      'Consultation en cabinet',
      'Consultation à distance',
      'Consultation écrite',
      'Avis juridique',
      'Analyse d’une situation juridique',
      'Étude d’un dossier',
      'Étude d’un contrat',
      'Second avis juridique',
      'Mise en demeure',
      'Lettre d’avocat',
      'Lettre de réclamation',
      'Requête',
      'Assignation',
      'Conclusions',
      'Mémoire',
      'Réplique',
      'Acte d’avocat',
      'Contrat',
      'Convention',
      'Protocole d’accord',
      'Transaction',
      'Négociation',
      'Conciliation',
      'Médiation avec assistance d’avocat',
      'Protocole transactionnel',
      'Ouverture d’un dossier contentieux',
      'Constitution d’avocat',
      'Préparation de la procédure',
      'Suivi de procédure',
      'Représentation devant les juridictions',
      'Défense du demandeur',
      'Défense du défendeur',
      'Plaidoirie',
      'Voies de recours',
      'Consultation pénale',
      'Assistance d’un suspect',
      'Défense d’un prévenu',
      'Constitution de partie civile',
      'Demande de mise en liberté',
      'Mise en demeure de payer',
      'Recouvrement amiable',
      'Recouvrement judiciaire',
      'Action en paiement',
      'Exécution d’une décision de justice',
      'Constitution de société',
      'Rédaction de statuts',
      'Pacte d’associés',
      'Conseil aux dirigeants',
      'Secrétariat juridique',
      'Divorce',
      'Séparation',
      'Pension alimentaire',
      'Garde des enfants',
      'Litige foncier',
      'Litige locatif',
      'Licenciement',
      'Recours administratif',
      'Contentieux administratif',
      'Assistance en arbitrage',
      'Droit OHADA',
      'Demande d’assistance judiciaire',
    ],
    ProfessionalServiceCategory.bailiffs => const [
      'Signification d’actes judiciaires',
      'Signification d’actes extrajudiciaires',
      'Signification de décisions de justice',
      'Signification de jugements',
      'Signification d’ordonnances',
      'Signification de citations',
      'Signification de convocations',
      'Signification de mises en demeure',
      'Procès-verbal de signification',
      'Constat matériel',
      'Constat avant travaux',
      'Constat de dommages',
      'Constat d’occupation des lieux',
      'Constat d’abandon',
      'Constat d’affichage',
      'Constat sur des biens',
      'Constat sur des contenus numériques',
      'Exécution d’un jugement',
      'Exécution d’un arrêt',
      'Exécution d’une ordonnance',
      'Exécution d’un titre exécutoire',
      'Commandement de payer',
      'Commandement de libérer les lieux',
      'Mise en œuvre des mesures d’exécution',
      'Suivi de l’exécution',
      'Procès-verbal d’exécution',
      'Recouvrement amiable',
      'Recouvrement forcé',
      'Relance du débiteur',
      'Encaissement des sommes recouvrées',
      'Saisie-vente',
      'Saisie-attribution',
      'Saisie conservatoire',
      'Saisie de biens',
      'Saisie de créances',
      'Saisie de comptes bancaires',
      'Procès-verbal de saisie',
      'Dénonciation de saisie',
      'Mainlevée de saisie',
      'Procédure d’expulsion',
      'Procès-verbal d’expulsion',
      'Procès-verbal de reprise des lieux',
      'Inventaire',
      'Description des biens',
      'Vente publique de meubles',
      'Vente de biens saisis',
      'Procès-verbal de vente',
      'Procès-verbal de carence',
      'Procès-verbal de difficultés',
      'Exploit d’huissier',
      'Vérification du titre exécutoire',
      'Suivi des délais de procédure',
    ],
    ProfessionalServiceCategory.jurisconsult => const [
      'Consultation juridique',
      'Consultation à distance',
      'Consultation écrite',
      'Analyse d’une situation juridique',
      'Orientation juridique',
      'Avis juridique',
      'Second avis juridique',
      'Recherche de textes applicables',
      'Recherche jurisprudentielle',
      'Recherche doctrinale',
      'Analyse de la législation',
      'Analyse de jurisprudence',
      'Veille juridique',
      'Étude juridique approfondie',
      'Note de recherche juridique',
      'Note juridique',
      'Note de synthèse',
      'Étude juridique',
      'Lettre juridique',
      'Courrier juridique',
      'Projet de contrat',
      'Projet de convention',
      'Projet de protocole',
      'Projet de règlement',
      'Projet de statuts',
      'Analyse de contrat',
      'Analyse de convention',
      'Analyse de statuts',
      'Analyse d’un acte juridique',
      'Vérification de clauses',
      'Identification des risques juridiques',
      'Vérification de conformité juridique',
      'Proposition de modifications',
      'Explication d’un document juridique',
      'Conseil juridique aux entreprises',
      'Conseil en droit des affaires',
      'Conseil en droit des sociétés',
      'Conseil en droit OHADA',
      'Accompagnement juridique des dirigeants',
      'Accompagnement des associés',
      'Audit juridique',
      'Audit contractuel',
      'Audit documentaire',
      'Cartographie des risques juridiques',
      'Analyse des obligations légales',
      'Mise en conformité documentaire',
      'Suivi réglementaire',
      'Recherche de lois',
      'Recherche de décrets',
      'Recherche d’arrêtés',
      'Recherche de règlements',
      'Recherche d’actes uniformes OHADA',
      'Recherche de textes administratifs',
      'Constitution de dossiers documentaires',
      'Formation juridique',
      'Formation en droit des affaires',
      'Formation en droit OHADA',
      'Formation en droit du travail',
      'Formation en droit des contrats',
      'Formation en droit des sociétés',
      'Formation juridique pour entreprises',
      'Formation juridique pour associations',
      'Accompagnement des étudiants en droit',
      'Identification du problème juridique',
      'Identification des textes applicables',
      'Orientation vers la procédure appropriée',
      'Orientation vers le professionnel compétent',
      'Orientation vers un avocat',
      'Orientation vers un notaire',
      'Orientation vers un huissier de justice',
      'Orientation vers une administration compétente',
      'Veille législative',
      'Veille réglementaire',
      'Veille jurisprudentielle',
      'Veille OHADA',
      'Veille UEMOA',
      'Veille fiscale',
      'Veille sociale',
      'Création d’entreprise et d’association',
      'Création de sociétés',
      'Création de coopératives',
      'Consultation approfondie',
    ],
  };
}
